export const COUNTRY_PROVINCE_LIST = {
  Canada: {
    en: "Canada",
    fr: "le Canada",
    provinces: [
      { en: "Alberta", fr: "l’Alberta" },
      { en: "British Columbia", fr: "la Colombie-Britannique" },
      { en: "Manitoba", fr: "le Manitoba" },
      { en: "NewBrunswick", fr: "le Nouveau-Brunswick" },
      { en: "Newfoundland and Labrador", fr: "la Terre-Neuve-et-Labrador" },
      { en: "Northwest Territories", fr: "les Territoires du Nord-Ouest" },
      { en: "Nova Scotia", fr: "la Nouvelle-Écosse" },
      { en: "Nunavut", fr: "le Nunavut" },
      { en: "Ontario", fr: "l’Ontario" },
      { en: "Prince Edward Island", fr: "l’île du Prince-Édouard" },
      { en: "Quebec", fr: "le Québec" },
      { en: "Saskatchewan", fr: "la Saskatchewan*" },
      { en: "Yukon", fr: "le Yukon" },
    ],
  },
  USA: {
    en: "United States of America",
    fr: "les états-unis d'Amérique",
    provinces: [
      { en: "Alabama", fr: "l’Alabama" },
      { en: "Alaska", fr: "l’Alaska" },
      { en: "Arizona", fr: "l’Arizona" },
      { en: "Arkansas", fr: "l’Arkansas" },
      { en: "California", fr: "la Californie" },
      { en: "Colorado", fr: "le Colorado" },
      { en: "Connecticut", fr: "le Connecticut" },
      { en: "Delaware", fr: "le Delaware" },
      { en: "Florida", fr: "la Floride" },
      { en: "Georgia", fr: "la Géorgie" },
      { en: "Hawaii", fr: "Hawaï" },
      { en: "Idaho", fr: "l’Idaho" },
      { en: "Illinois", fr: "l’Illinois" },
      { en: "Indiana", fr: "l’Indiana" },
      { en: "Iowa", fr: "l’Iowa" },
      { en: "Kansas", fr: "le Kansas" },
      { en: "Kentucky", fr: "le Kentucky" },
      { en: "Louisiana", fr: "la Louisiane" },
      { en: "Maine", fr: "le Maine" },
      { en: "Maryland", fr: "le Maryland" },
      { en: "Massachusetts", fr: "le Massachusetts" },
      { en: "Michigan", fr: "le Michigan" },
      { en: "Minnesota", fr: "le Minnesota" },
      { en: "Mississippi", fr: "le Mississippi" },
      { en: "Missouri", fr: "le Missouri" },
      { en: "Montana", fr: "le Montana" },
      { en: "Nebraska", fr: "le Nebraska" },
      { en: "Nevada", fr: "le Nevada" },
      { en: "New Hampshire", fr: "le New Hampshire" },
      { en: "New Jersey", fr: "le New Jersey" },
      { en: "New Mexico", fr: "le Nouveau-Mexique" },
      { en: "New York", fr: "l’État de New York" },
      { en: "North Carolina", fr: "la Caroline du Nord" },
      { en: "North Dakota", fr: "le Dakota du Nord" },
      { en: "Ohio", fr: "l’Ohio" },
      { en: "Oklahoma", fr: "l’Oklahoma" },
      { en: "Oregon", fr: "l’Oregon" },
      { en: "Pennsylvania", fr: "la Pennsylvanie" },
      { en: "Rhode Island", fr: "le Rhode Island" },
      { en: "South Carolina", fr: "la Caroline du Sud" },
      { en: "South Dakota", fr: "le Dakota du Sud" },
      { en: "Tennessee", fr: "le Tennessee" },
      { en: "Texas", fr: "le Texas" },
      { en: "Utah", fr: "l’Utah" },
      { en: "Vermont", fr: "le Vermont" },
      { en: "Virginia", fr: "la Virginie" },
      { en: "Washington", fr: "l’État de Washington" },
      { en: "West Virginia", fr: "la Virginie-Occidentale" },
      { en: "Wisconsin", fr: "le Wisconsin" },
      { en: "Wyoming", fr: "le Wyoming" },
    ],
  },
};
